import { css } from '@emotion/react';
import Head from 'next/head';
import { Button, Card, Carousel, Col, Container, Row } from 'react-bootstrap';
import { GetAllProducts } from '../util/Database';

type IndexProps = {
  productsToDisplay: Product[];
};

export default function Home(props: IndexProps) {
  const firstRow = props.productsToDisplay.slice(0, 3);
  const secondRow = props.productsToDisplay.slice(3, 6);
  const thirdRow = props.productsToDisplay.slice(6, 9);

  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <Carousel variant="dark">
          <Carousel.Item>
            <img
              className="d-block w-100 h-70"
              src="https://hinacreates.com/wp-content/uploads/2021/06/dummy2.png"
              alt="First slide"
            />
            <Carousel.Caption>
              <h3>First slide label</h3>
              <p>Nulla vitae elit libero, a pharetra augue mollis interdum.</p>
            </Carousel.Caption>
          </Carousel.Item>
          <Carousel.Item>
            <img
              className="d-block w-100 h-70"
              src="https://hinacreates.com/wp-content/uploads/2021/06/dummy2.png"
              alt="Second slide"
            />

            <Carousel.Caption>
              <h3>Second slide label</h3>
              <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit.</p>
            </Carousel.Caption>
          </Carousel.Item>
          <Carousel.Item>
            <img
              className="d-block w-100 h-70"
              src="https://hinacreates.com/wp-content/uploads/2021/06/dummy2.png"
              alt="Third slide"
            />

            <Carousel.Caption>
              <h3>Third slide label</h3>
              <p>
                Praesent commodo cursus magna, vel scelerisque nisl consectetur.
              </p>
            </Carousel.Caption>
          </Carousel.Item>
        </Carousel>

        <Container>
          <Row>
            {firstRow.map((product) => {
              return (
                <Col
                  key={product.product_name}
                  style={{ marginTop: '20px' }}
                  md={4}
                >
                  <Card
                    style={{
                      height: '100%',
                    }}
                  >
                    <Card.Img variant="top" src={product.product_imgpath} />
                    <Card.Body>
                      <Card.Title>{product.product_name}</Card.Title>
                      <Card.Text>
                        {product.product_description} {product.product_price}
                      </Card.Text>
                      <Button
                        variant="primary"
                        href={`/${product.product_slug}`}
                        data-test-id={`product-${product.product_slug}`}
                      >
                        Go to product
                      </Button>
                    </Card.Body>
                  </Card>
                </Col>
              );
            })}
          </Row>
          <Row>
            {secondRow.map((product) => {
              return (
                <Col
                  key={product.product_name}
                  style={{ marginTop: '20px' }}
                  md={4}
                >
                  <Card>
                    <Card.Img variant="top" src={product.product_imgpath} />
                    <Card.Body>
                      <Card.Title>{product.product_name}</Card.Title>
                      <Card.Text>
                        {product.product_description} {product.product_price}
                      </Card.Text>
                      <Button
                        variant="primary"
                        href={`/${product.product_slug}`}
                        data-test-id={`product-${product.product_slug}`}
                      >
                        Go to product
                      </Button>
                    </Card.Body>
                  </Card>
                </Col>
              );
            })}
          </Row>
          <Row>
            {thirdRow.map((product) => {
              return (
                <Col
                  key={product.product_name}
                  style={{ marginTop: '20px' }}
                  md={4}
                >
                  <Card>
                    <Card.Img variant="top" src={product.product_imgpath} />
                    <Card.Body>
                      <Card.Title>{product.product_name}</Card.Title>
                      <Card.Text>
                        {product.product_description} {product.product_price}
                      </Card.Text>
                      <Button
                        variant="primary"
                        href={`/${product.product_slug}`}
                        data-test-id={`product-${product.product_slug}`}
                      >
                        Go to product
                      </Button>
                    </Card.Body>
                  </Card>
                </Col>
              );
            })}
          </Row>
        </Container>
      </main>
    </div>
  );
}

export async function getServerSideProps() {
  const products = await GetAllProducts();

  return {
    props: {
      productsToDisplay: products,
    },
  };
}
